### ISSUE TITLE
이미지 업로드가 포함된 api 전체 반영

### ISSUE THREAD

**Issue by Starlight258** [Step3-kakao-tech-campus/Team10_BE#87]
## 이미지 업로드가 포함된 api
- [x] 세차장 등록
- [x] 개별 매장 수정 - 수정된 정보 적용하기
    <수정시 기존 이미지에 이미지 추가>
## 이미지 entity가 포함된 api
- [x] 세차장 상세 정보 조회 (리뷰 제외)
- [x] 현재 시간 기준 예약 내역 조회
- [x] 최근 예약 내역 가져오기
- [x] 개별 매장 수정 - 기존 정보 불러오기
- [x] 매장 관리 - owner별, 세차장별
- [x] 사장님 홈

**Comment by Cheoroo** [comment]
세차장별 예약 내역 조회도 수정햇습니당

**Comment by Starlight258** [comment]
에러가 발생하네요 ㅠ

**Comment by Starlight258** [comment]
이미지 반영 완료
